---
- hosts: localhost
  tasks:
    - name: add the new server IP address to hosts file
      lineinfile:
           path: /home/nsangadala/oracle-linux-playbooks/hosts
           insertafter: '\[localhost\]\nlocal-host-ipaddress\n'
           regexp: '^\[localhost\]\nlocal-host-aiaddress\n'
           line: '[new-host-name]'

    - name: add the new server IP address to hosts file
      lineinfile:
           path: /home/nsangadala/oracle-linux-playbooks/hosts
           insertafter: '^\[new-host-name\]'
           regexp: '^\[new-host-name\]'
           line: 'new-host-ipaddress'
